### ISSUE TITLE
ck2plus / cleanslate

### ISSUE THREAD

**Issue by blendcs** [ck2plus/CK2Plus#280]
hi.
im new here and im noob in moding, but im wondering, why is ck2plus and cleanslate mods not merged into one mod?
If ckplus+ req. cleanslate, it is for me logical to do so?
i like play ck2 but i like to change some of the files littlebit. 
now with 2 mods i do not know which files in which folders I should change in mod folder.

For ex. i would like to add modifier to one of the culture and add some changes into landet_titles.
So where exactly i should make changes? into ck2plus or cleanslate?

**Comment by Whizzer** [comment]
Those changes would be made in CK2+ files, since that's the mod you're seeking to change.
The reason the mods are separate is the same reason any other mod only contains vanilla files that have been changed. CleanSlate effectively replaces vanilla CK2, and so CK2+ only contains CleanSlate files that have been changed.

**Comment by blendcs** [comment]
but why it is that, when I unzip cleanslate files an lauch ck2, in mod folder appears ck2+ folder?

**Comment by schwarherz** [comment]
This is not the place for discussions. This is for bug/issue reports. [Please visit our discord for discussions.](https://discord.gg/JeVamzTkJZ)
